openapi: 3.0.3
info:
  title: ratings API
  description: ratings API
  version: 1.0.0
servers:
  - url: 'http://185.231.155.86:8080'
components:
  schemas:
    review:
      type: object
      properties:
        username:
          required: true
          type: string
        game:
          required: true
          type: string
        rating:
          required: true
          type: integer
        text:
          required: false
          type: string
paths:
  /v1/post-review:
    post:
      description: creates new review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/review'
      responses:
        200:
          description: OK, returns time of database row creation
          content:
            text/plain:
              schema:
                description: timing of creation
                type: string
  /v1/get-reviews:
    get:
      description: returns all reviews matching request
      parameters:
        - name: username
          in: query
          description: username to search for
          required: false
        - name: game
          in: query
          description: game to search for
          required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/review'
