on:
  push:
    branches:
      - release
      - feature/docker
jobs:
  run-check:
    runs-on: ubuntu-latest
    outputs:
      pr_number_opt: ${{ steps.check.outputs.pr_number_opt }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Check if commit is a result of a merged pull request
        id: check
        #check if last commit message has correct naming, containing '(#NUMBERS)', e.g. https://github.com/nfrmtk/ratings/commit/e78c8e93d42cf16953d341ed2c4364f7194c3540
        run: |
          pr_number_opt=$(echo '${{ github.event.commits[0].pr_number_opt }}' | python pr_number_or_bad_commit.py)
          echo "::set-output name=pr_numer_opt::${pr_number_opt}"

  push:
    needs: run-check
    name: push
    if: needs.run-check.outputs.pr_number_opt != 'bad-commit'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ratings:${{ needs.run-check.outputs.pr_number_opt }}
