on:
  push:
    branches:
      - release
      - feature/docker
      - feature/better-docker
jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push service
        uses: docker/build-push-action@v4
#        if: github.ref != 'refs/heads/feature/better-docker'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ratings:latest
      -
        name: Build and push postgres
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-postgres-with-volumes
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ratings-postgres:latest

